### ISSUE TITLE
The problem in the process of replicating the code

### ISSUE THREAD

**Issue by songyuanbing6** [edvardlindelof/graph-neural-networks-for-drug-discovery#2]
I am replicating your code.The Training score ,Validation Score and Test Score are all lower than yours.

I want to know,is the dataset you gave in toydata(Piece of Tox21)  complete?

**Comment by edvardlindelof** [comment]
Hi songyuanbing6,

The files in toydata/ are not complete, but contain only a couple of molecules each and are checked in to the code for debugging purposes.

**Comment by songyuanbing6** [comment]
I am honored to receive your reply. Thank you for your reply.

Could you please provide the complete dataset you used? I would like to replicate the same result as you got.

Thank you very much.

**Comment by edvardlindelof** [comment]
We loaded the datasets using deepchem utilities. See these: https://github.com/deepchem/deepchem/tree/master/deepchem/molnet/load_function and corresponding documentation

**Comment by songyuanbing6** [comment]
OK.Thank you very much for your help.

**Comment by songyuanbing6** [comment]
Thank you for your guidance. 
According to your guidance，I ran tox21_datasets.py. 
Then the mistake was happened.(ImportError: cannot import name 'jaccard_score')
How do I solve this problem ?  I hope to get your help.
